name: Maven Central Repo Deployment
on:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build project
        run: |
          java -version
          mvn -version
          mvn clean install -B -U -e -Prelease
      - name: Deploy snapshot artifacts
        run: |
          echo "<settings><servers><server><id>ossrh</id><username>${{ secrets.OSSRH_USER }}</username><password>${{ secrets.OSSRH_PASSWORD }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
          mvn deploy -Prelease -B -e -Dmaven.test.skip=true
