name: Publish package to the Maven Central Repository
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: GPG_PRIVATE_KEY
          gpg-passphrase: GPG_PASSPHRASE
      - name: Publish package
        run: mvn deploy -Pdeploy -B -e -Dmaven.test.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SECRET }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
